### ISSUE TITLE
esp32c6bugethernet.ino example header missing

### ISSUE THREAD

**Issue by coopper5120** [allexoK/Esp32-C6-Bug-Arduino-Examples#4]
There is a problem with compilation of esp32c6bugethernet.ino example.

I currently use esp 3.0.0 board manager and there are compilation errors due to lack of:

#include <WiFi.h>

**Comment by allexoK** [comment]
Hi, @coopper5120, thx, I will take a look at it tomorrow

**Comment by allexoK** [comment]
Should be fixed in b8e1350
